import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './app/components/**/*.{vue,js,ts}',
    './app/layouts/**/*.vue',
    './app/pages/**/*.vue',
    './app/app.vue',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#c8c6c5',
        'on-primary': '#640036',
        'surface-container': '#20201f',
        error: '#ffb4ab',
        'surface-dim': '#131313',
        'inverse-primary': '#b90068',
        'primary-fixed': '#ffd9e3',
        background: '#131313',
        'primary-fixed-dim': '#ffb0ca',
        'on-tertiary-container': '#292a2a',
        'on-background': '#e5e2e1',
        primary: '#ffb0ca',
        'on-error': '#690005',
        'on-surface-variant': '#e3bdc7',
        'surface-container-highest': '#353535',
        'on-primary-fixed': '#3e001f',
        'on-primary-container': '#58002f',
        'primary-container': '#ff479c',
        surface: '#131313',
        secondary: '#c8c6c5',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-fixed-variant': '#8d004e',
        'surface-tint': '#ffb0ca',
        'on-error-container': '#ffdad6',
        'outline-variant': '#5b3f48',
        'on-tertiary-fixed-variant': '#464747',
        'on-secondary-fixed': '#1c1b1b',
        'inverse-surface': '#e5e2e1',
        'on-secondary': '#313030',
        'secondary-container': '#4a4949',
        'surface-variant': '#353535',
        'on-tertiary-fixed': '#1a1c1c',
        'inverse-on-surface': '#313030',
        'surface-container-low': '#1c1b1b',
        'surface-bright': '#393939',
        'tertiary-fixed-dim': '#c7c6c6',
        'surface-container-high': '#2a2a2a',
        'on-surface': '#e5e2e1',
        'tertiary-container': '#909191',
        tertiary: '#c7c6c6',
        'secondary-fixed': '#e5e2e1',
        'on-secondary-fixed-variant': '#474646',
        'error-container': '#93000a',
        'on-secondary-container': '#bab8b7',
        'on-tertiary': '#2f3131',
        'tertiary-fixed': '#e3e2e2',
        outline: '#aa8892',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter-desktop': '32px',
        'gutter-mobile': '16px',
        unit: '4px',
        'section-gap': '80px',
        'margin-safe': '24px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'headline-xl': ['Space Grotesk', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '600' }],
        'headline-xl': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' },
        ],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
} satisfies Config
